import Foundation

/// The herdr config Mori writes for its own session.
///
/// Mori hosts herdr's *full* client inside a Ghostty surface rather than using
/// `herdr terminal attach`, because only the foreground client gets mouse reporting and
/// kitty graphics. The price is herdr's own chrome, which this config turns off: Mori
/// already draws the sidebar, the tab bar, and the pane borders.
public struct HerdrConfig: Sendable, Hashable {
    /// Mori draws its own sidebar, so herdr's is collapsed…
    public var sidebarStartCollapsed: Bool
    /// …and collapsed to nothing rather than to a strip of icons.
    public var sidebarCollapsedMode: String
    /// Mori draws its own tab bar. herdr has no "always hide" mode yet (see Phase 10), so a
    /// second row still appears once a workspace has two or more tabs.
    public var hideTabBarWhenSingleTab: Bool
    public var paneBorders: Bool
    /// Left at herdr's default: this is the configuration the POC measured mouse reporting
    /// and kitty graphics working under. Turning it off is untested, not obviously better.
    public var mouseCapture: Bool
    /// Without this even the full client drops inline images; Yazi previews depend on it.
    public var kittyGraphics: Bool

    public init(
        sidebarStartCollapsed: Bool = true,
        sidebarCollapsedMode: String = "hidden",
        hideTabBarWhenSingleTab: Bool = true,
        paneBorders: Bool = false,
        mouseCapture: Bool = true,
        kittyGraphics: Bool = true
    ) {
        self.sidebarStartCollapsed = sidebarStartCollapsed
        self.sidebarCollapsedMode = sidebarCollapsedMode
        self.hideTabBarWhenSingleTab = hideTabBarWhenSingleTab
        self.paneBorders = paneBorders
        self.mouseCapture = mouseCapture
        self.kittyGraphics = kittyGraphics
    }

    public func render() -> String {
        """
        # Generated by Mori — edits are overwritten on launch.
        # This configures Mori's own herdr session only; your ~/.config/herdr/config.toml
        # and your `default` session are untouched.

        [ui]
        sidebar_start_collapsed = \(sidebarStartCollapsed)
        sidebar_collapsed_mode = "\(sidebarCollapsedMode)"
        hide_tab_bar_when_single_tab = \(hideTabBarWhenSingleTab)
        pane_borders = \(paneBorders)
        mouse_capture = \(mouseCapture)

        [experimental]
        kitty_graphics = \(kittyGraphics)

        """
    }
}

public enum HerdrConfigWriter {
    /// Writes the config, creating the directory if needed.
    ///
    /// Returns whether anything changed, so a caller can skip asking a running server to
    /// reload for an identical file.
    @discardableResult
    public static func write(_ config: HerdrConfig, to path: String) throws -> Bool {
        let rendered = config.render()
        if let existing = try? String(contentsOfFile: path, encoding: .utf8), existing == rendered {
            return false
        }
        try FileManager.default.createDirectory(
            atPath: (path as NSString).deletingLastPathComponent,
            withIntermediateDirectories: true
        )
        try rendered.write(toFile: path, atomically: true, encoding: .utf8)
        return true
    }
}
