#!/usr/bin/env bash
# Verify the Mori-built universal GhosttyKit layout, provenance, and remux tmux C ABI.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=ghosttykit-contract.sh
source "$repo_root/scripts/ghosttykit-contract.sh"

xcframework="${MORI_GHOSTTYKIT_XCFRAMEWORK:-$repo_root/Frameworks/GhosttyKit.xcframework}"
provenance_path="$(dirname "$xcframework")/.ghosttykit-provenance"

fail() {
    echo "GhosttyKit verification failed: $*" >&2
    exit 1
}

[[ -f "$xcframework/Info.plist" ]] || fail "missing Info.plist at $xcframework"
[[ -f "$provenance_path" ]] || fail "missing provenance record at $provenance_path"

read_provenance() {
    local key="$1"
    awk -F= -v key="$key" '$1 == key { print substr($0, length(key) + 2); exit }' "$provenance_path"
}
[[ "$(read_provenance source_commit)" == "$MORI_GHOSTTYKIT_SOURCE_COMMIT" ]] || fail "unexpected source commit"
[[ "$(read_provenance source_version)" == "$MORI_GHOSTTYKIT_VERSION" ]] || fail "unexpected explicit Ghostty version"
[[ "$(read_provenance xcframework_target)" == "universal" ]] || fail "artifact was not built with the universal target"
[[ "$(read_provenance optimize)" == "$MORI_GHOSTTYKIT_OPTIMIZE" ]] || fail "unexpected optimization mode"

# Retain a content-integrity check in addition to the source pin. The digest is
# generated by the same trusted workflow that builds the artifact, then checked
# before any consuming job builds or archives an app.
framework_tree_sha256() {
    local root="$1"
    find "$root" -type f -print0 | LC_ALL=C sort -z | while IFS= read -r -d '' file; do
        printf '%s  %s\n' "$(shasum -a 256 "$file" | awk '{print $1}')" "${file#"$root"/}"
    done | shasum -a 256 | awk '{print $1}'
}
expected_tree_sha256="$(read_provenance framework_tree_sha256)"
[[ "$expected_tree_sha256" =~ ^[0-9a-f]{64}$ ]] || fail "missing framework content digest"
[[ "$(framework_tree_sha256 "$xcframework")" == "$expected_tree_sha256" ]] || fail "framework files do not match the provenance content digest"

# Every consumer must use the same source pin as the artifact. This catches a
# stale framework restored from cache even when its writable provenance file is
# copied alongside it.
if [[ -d "$repo_root/vendor/ghostty/.git" || -f "$repo_root/vendor/ghostty/.git" ]]; then
    [[ "$(git -C "$repo_root/vendor/ghostty" rev-parse HEAD)" == "$MORI_GHOSTTYKIT_SOURCE_COMMIT" ]] || fail "checked-out Ghostty source does not match the contract"
fi

# This release must support macOS plus iOS 17's device and Apple Silicon simulator SDKs.
for slice in macos-arm64_x86_64 ios-arm64 ios-arm64-simulator; do
    headers="$xcframework/$slice/Headers"
    [[ -f "$headers/ghostty.h" ]] || fail "missing $slice header"
    [[ -f "$headers/module.modulemap" ]] || fail "missing $slice module map"
done

macos_library="$xcframework/macos-arm64_x86_64/libghostty-internal-fat.a"
[[ -f "$macos_library" ]] || fail "missing macOS static library"
[[ "$(lipo -archs "$macos_library")" == *"arm64"* && "$(lipo -archs "$macos_library")" == *"x86_64"* ]] || fail "macOS slice is not universal"

for slice in ios-arm64 ios-arm64-simulator; do
    library="$xcframework/$slice/libghostty-internal-fat.a"
    [[ -f "$library" ]] || fail "missing $slice static library"
    [[ "$(lipo -archs "$library")" == *"arm64"* ]] || fail "$slice lacks arm64"
done

# XCFramework metadata must identify a device and an Apple Silicon simulator slice.
plist_xml="$(plutil -extract AvailableLibraries xml1 -o - "$xcframework/Info.plist")"
printf '%s' "$plist_xml" | grep -q '<string>macos-arm64_x86_64</string>' || fail "missing macOS metadata"
printf '%s' "$plist_xml" | grep -q '<string>ios-arm64</string>' || fail "missing ios-arm64 metadata"
printf '%s' "$plist_xml" | grep -q '<string>ios-arm64-simulator</string>' || fail "missing ios-arm64-simulator metadata"
printf '%s' "$plist_xml" | grep -q '<string>simulator</string>' || fail "missing simulator platform variant"

# Compiling these declarations for both SDKs catches header/API drift. Linking
# is verified by Xcode, where it selects the XCFramework slice.
probe_source="$(mktemp "${TMPDIR:-/tmp}/mori-ghosttykit-abi.XXXXXX.c")"
trap 'rm -f "$probe_source" "${probe_source%.c}".*' EXIT
cat >"$probe_source" <<'SOURCE'
#include <ghostty.h>
int remux_tmux_abi_probe(void) {
    ghostty_tmux_client_config_s config = ghostty_tmux_client_config_new();
    return (int)config.initial_columns + (int)ghostty_info().build_mode;
}
SOURCE
for sdk in iphoneos iphonesimulator; do
    sdk_path="$(xcrun --sdk "$sdk" --show-sdk-path)"
    slice="ios-arm64"
    target="arm64-apple-ios17.0"
    if [[ "$sdk" == "iphonesimulator" ]]; then
        slice="ios-arm64-simulator"
        target="arm64-apple-ios17.0-simulator"
    fi
    xcrun --sdk "$sdk" clang -target "$target" \
        -isysroot "$sdk_path" -fmodules -I "$xcframework/$slice/Headers" \
        -c "$probe_source" -o "${probe_source%.c}.$sdk.o"
done

# The iOS binaries cannot execute on the build host. The universal macOS slice
# gives the same artifact a runnable release-mode gate.
macos_probe="${probe_source%.c}.macos"
xcrun --sdk macosx clang -target "$(uname -m)-apple-macos15.0" \
    -I "$xcframework/macos-arm64_x86_64/Headers" -x c - -x none "$macos_library" \
    -lc++ -framework Foundation -framework AppKit -framework Metal \
    -framework QuartzCore -framework IOSurface -framework Carbon -o "$macos_probe" <<'SOURCE'
#include <stdio.h>
#include <ghostty.h>
int main(void) { printf("%d\n", (int)ghostty_info().build_mode); }
SOURCE
[[ "$("$macos_probe")" == "2" ]] || fail "artifact is not Ghostty ReleaseFast (build mode 2)"

# Header declarations alone are insufficient; require the custom tmux symbols
# from the macOS and both iOS static-library slices.
for library in "$macos_library" "$xcframework/ios-arm64/libghostty-internal-fat.a" "$xcframework/ios-arm64-simulator/libghostty-internal-fat.a"; do
    symbols="$(nm -gU "$library")"
    for symbol in _ghostty_info _ghostty_tmux_client_config_new _ghostty_tmux_client_new _ghostty_tmux_client_feed _ghostty_tmux_client_outbound _ghostty_tmux_client_consume; do
        grep -q "${symbol}$" <<<"$symbols" || fail "$(basename "$(dirname "$library")") lacks $symbol"
    done
done

# All iOS object files must declare a deployment target no newer than iOS 17.
for slice in ios-arm64 ios-arm64-simulator; do
    minos_values="$(otool -l "$xcframework/$slice/libghostty-internal-fat.a" | awk '/minos / { print $2 }' | sort -u)"
    [[ -n "$minos_values" ]] || fail "$slice has no LC_BUILD_VERSION minimum OS metadata"
    while IFS= read -r minos; do
        major="${minos%%.*}"
        [[ "$major" =~ ^[0-9]+$ && "$major" -le "$MORI_GHOSTTYKIT_MIN_IOS_MAJOR" ]] || fail "$slice requires iOS $minos, above the iOS $MORI_GHOSTTYKIT_MIN_IOS_MAJOR contract"
    done <<<"$minos_values"
done

printf 'Verified Mori-built GhosttyKit %s: universal macOS, iOS 17 device/simulator arm64 slices, and remux tmux ABI.\n' "$MORI_GHOSTTYKIT_SOURCE_COMMIT"
